# Added for editor completions
"$schema" = 'https://starship.rs/config-schema.json'

# Add newline before new prompts
add_newline = true

# But keep the input on the same line as the prompt
[line_break]
disabled = true

[aws]
disabled = true

[bun]
format = "[$symbol]($style)"

[buf]
format = "[$symbol]($style)"

[c]
format = "[$symbol($name)]($style)"

[cmake]
format = "[$symbol]($style)"

[cobol]
format = "[$symbol]($style)"

[cpp]
format = "[$symbol($name)]($style)"

[crystal]
format = "[$symbol]($style)"

[daml]
format = "[$symbol]($style)"

[dart]
format = "[$symbol]($style)"

[deno]
format = "[$symbol]($style)"

[docker_context]
format = "[$symbol]($style)"

[dotnet]
disabled = true
# format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
format = '[$symbol]($style)'

[elm]
format = '[$symbol]($style)'

[erlang]
format = '[$symbol]($style)'

[fennel]
format = '[$symbol]($style)'

[fortran]
format = '[$symbol]($style)'

[gleam]
format = '[$symbol]($style)'

[golang]
format = '[$symbol]($style)'

[gradle]
format = '[$symbol]($style)'

[haskell]
format = '[$symbol]($style)'

[haxe]
format = '[$symbol]($style)'

[helm]
format = '[$symbol]($style)'

[java]
format = '[$symbol]($style)'

[julia]
format = '[$symbol]($style)'

[kotlin]
format = '[$symbol]($style)'

[lua]
format = '[$symbol]($style)'

[meson]
format = '[$symbol]($style)'

[mojo]
format = '[$symbol]($style)'

[nim]
format = '[$symbol]($style)'

[nodejs]
format = '[$symbol]($style)'

[ocaml]
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)'

[odin]
format = '[$symbol]($style)'

[opa]
format = '[$symbol]($style)'

[package]
disabled = true

[perl]
format = '[$symbol]($style)'

[php]
format = '[$symbol]($style)'

[pixi]
format = '[$symbol($environment )]($style)'

[pulumi]
format = '[$symbol$stack]($style)'

[purescript]
format = '[$symbol]($style)'

[python]
format = '[$symbol]($style)'

[quarto]
format = '[$symbol]($style)'

[raku]
format = '[$symbol]($style)'

[red]
format = '[$symbol]($style)'

[rlang]
format = '[$symbol]($style)'

[ruby]
format = '[$symbol]($style)'

[rust]
format = '[$symbol]($style)'

[scala]
format = '[$symbol]($style)'

[solidity]
format = '[$symbol]($style)'

[swift]
format = '[$symbol]($style)'

[typst]
format = '[$symbol]($style)'

[vagrant]
format = '[$symbol]($style)'

[vlang]
format = '[$symbol]($style)'

[xmake]
format = "[$symbol]($style)"

[zig]
format = '[$symbol]($style)'
